import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { 
  Bot, 
  Plus, 
  Trash2, 
  Play, 
  Square, 
  RefreshCw,
  Key,
  Server,
  Activity,
  CheckCircle,
  XCircle,
  Loader2
} from 'lucide-react';
import { toast } from 'sonner';

interface DockerBot {
  id: string;
  bot_name: string;
  bot_api_key: string;
  assigned_port: number;
  container_name: string;
  status: string;
  is_admin_bot: boolean;
  created_at: string;
  last_started_at: string | null;
  last_stopped_at: string | null;
}

// Auto-generate available ports starting from 3100
const getNextAvailablePort = (existingPorts: number[]): number => {
  let port = 3100;
  while (existingPorts.includes(port)) {
    port++;
  }
  return port;
};

export default function DockerBotManager() {
  const [bots, setBots] = useState<DockerBot[]>([]);
  const [loading, setLoading] = useState(true);
  const [adding, setAdding] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  
  // Form state
  const [botName, setBotName] = useState('');
  const [botApiKey, setBotApiKey] = useState('');
  const [autoGeneratedPort, setAutoGeneratedPort] = useState(3100);

  useEffect(() => {
    fetchBots();
  }, []);

  useEffect(() => {
    // Auto-generate port when existing bots change
    const existingPorts = bots.map(b => b.assigned_port);
    setAutoGeneratedPort(getNextAvailablePort(existingPorts));
  }, [bots]);

  const fetchBots = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('docker_bots')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setBots(data as DockerBot[]);
    } catch (error) {
      console.error('Error fetching bots:', error);
      toast.error('Failed to load docker bots');
    } finally {
      setLoading(false);
    }
  };

  const addBot = async () => {
    if (!botName.trim() || !botApiKey.trim()) {
      toast.error('Please fill in all fields');
      return;
    }

    setAdding(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      const containerName = botName.toLowerCase().replace(/[^a-z0-9]/g, '-');
      const existingPorts = bots.map(b => b.assigned_port);
      const port = getNextAvailablePort(existingPorts);

      const { data, error } = await supabase
        .from('docker_bots')
        .insert({
          user_id: user?.id,
          bot_name: botName,
          bot_api_key: botApiKey,
          assigned_port: port,
          container_name: containerName,
          status: 'stopped',
          is_admin_bot: true
        })
        .select()
        .single();

      if (error) throw error;

      setBots(prev => [data as DockerBot, ...prev]);
      setBotName('');
      setBotApiKey('');
      setShowAddForm(false);
      toast.success(`Bot "${botName}" added on port ${port}`);
    } catch (error) {
      console.error('Error adding bot:', error);
      toast.error('Failed to add bot');
    } finally {
      setAdding(false);
    }
  };

  const toggleBotStatus = async (bot: DockerBot) => {
    const newStatus = bot.status === 'running' ? 'stopped' : 'running';
    
    try {
      const updateData: any = {
        status: newStatus
      };
      
      if (newStatus === 'running') {
        updateData.last_started_at = new Date().toISOString();
      } else {
        updateData.last_stopped_at = new Date().toISOString();
      }

      const { error } = await supabase
        .from('docker_bots')
        .update(updateData)
        .eq('id', bot.id);

      if (error) throw error;

      setBots(prev => prev.map(b => 
        b.id === bot.id ? { ...b, ...updateData } : b
      ));

      toast.success(`Bot ${newStatus === 'running' ? 'started' : 'stopped'}`);
    } catch (error) {
      console.error('Error toggling bot:', error);
      toast.error('Failed to update bot status');
    }
  };

  const deleteBot = async (botId: string, botName: string) => {
    if (!confirm(`Delete bot "${botName}"? This cannot be undone.`)) return;

    try {
      const { error } = await supabase
        .from('docker_bots')
        .delete()
        .eq('id', botId);

      if (error) throw error;

      setBots(prev => prev.filter(b => b.id !== botId));
      toast.success(`Bot "${botName}" deleted`);
    } catch (error) {
      console.error('Error deleting bot:', error);
      toast.error('Failed to delete bot');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-orange-500 to-red-600 flex items-center justify-center">
            <Bot className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Docker Bot Manager</h2>
            <p className="text-sm text-gray-400">Deploy bots automatically with API keys</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button 
            onClick={fetchBots}
            variant="outline"
            size="sm"
            className="gap-2"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </Button>
          <Button 
            onClick={() => setShowAddForm(!showAddForm)}
            size="sm"
            className="gap-2 bg-green-600 hover:bg-green-700"
          >
            <Plus className="w-4 h-4" />
            Add Bot
          </Button>
        </div>
      </div>

      {/* Add Bot Form */}
      {showAddForm && (
        <div className="bg-gray-800/50 rounded-xl border border-green-500/30 p-6">
          <h3 className="font-semibold text-white mb-4 flex items-center gap-2">
            <Key className="w-4 h-4 text-green-400" />
            Add New Bot to Docker
          </h3>
          
          <div className="grid gap-4">
            <div>
              <Label htmlFor="botName" className="text-gray-300">Bot Name</Label>
              <Input
                id="botName"
                placeholder="e.g., My Telegram Bot"
                value={botName}
                onChange={(e) => setBotName(e.target.value)}
                className="mt-1 bg-gray-900/50 border-white/10"
              />
            </div>
            
            <div>
              <Label htmlFor="apiKey" className="text-gray-300">Bot API Key (Token)</Label>
              <Input
                id="apiKey"
                type="password"
                placeholder="e.g., 123456789:ABCdefGHI..."
                value={botApiKey}
                onChange={(e) => setBotApiKey(e.target.value)}
                className="mt-1 bg-gray-900/50 border-white/10 font-mono"
              />
            </div>

            <div className="bg-gray-900/50 rounded-lg p-4 border border-white/5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-400">Auto-assigned Port</p>
                  <p className="text-2xl font-bold text-cyan-400 font-mono">{autoGeneratedPort}</p>
                </div>
                <div className="text-right">
                  <p className="text-sm text-gray-400">Container Name</p>
                  <p className="text-lg font-mono text-white">
                    {botName ? botName.toLowerCase().replace(/[^a-z0-9]/g, '-') : 'your-bot'}
                  </p>
                </div>
              </div>
            </div>

            <div className="flex gap-2">
              <Button 
                variant="outline" 
                onClick={() => setShowAddForm(false)}
                className="flex-1"
              >
                Cancel
              </Button>
              <Button 
                onClick={addBot}
                disabled={adding || !botName.trim() || !botApiKey.trim()}
                className="flex-1 bg-green-600 hover:bg-green-700"
              >
                {adding ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin mr-2" />
                    Deploying...
                  </>
                ) : (
                  <>
                    <Server className="w-4 h-4 mr-2" />
                    Deploy Bot
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-gray-800/50 rounded-xl p-4 border border-white/10">
          <div className="flex items-center gap-3">
            <Server className="w-8 h-8 text-blue-400" />
            <div>
              <p className="text-2xl font-bold text-white">{bots.length}</p>
              <p className="text-xs text-gray-400">Total Bots</p>
            </div>
          </div>
        </div>
        <div className="bg-gray-800/50 rounded-xl p-4 border border-white/10">
          <div className="flex items-center gap-3">
            <Activity className="w-8 h-8 text-green-400" />
            <div>
              <p className="text-2xl font-bold text-white">{bots.filter(b => b.status === 'running').length}</p>
              <p className="text-xs text-gray-400">Running</p>
            </div>
          </div>
        </div>
        <div className="bg-gray-800/50 rounded-xl p-4 border border-white/10">
          <div className="flex items-center gap-3">
            <Square className="w-8 h-8 text-gray-400" />
            <div>
              <p className="text-2xl font-bold text-white">{bots.filter(b => b.status === 'stopped').length}</p>
              <p className="text-xs text-gray-400">Stopped</p>
            </div>
          </div>
        </div>
      </div>

      {/* Bot List */}
      <div className="bg-gray-800/30 rounded-xl border border-white/10">
        <div className="p-4 border-b border-white/10">
          <h3 className="font-semibold text-white">Deployed Bots</h3>
        </div>
        
        <ScrollArea className="h-[400px]">
          {loading ? (
            <div className="p-8 text-center text-gray-400">
              <Loader2 className="w-8 h-8 animate-spin mx-auto mb-2" />
              Loading bots...
            </div>
          ) : bots.length === 0 ? (
            <div className="p-8 text-center text-gray-400">
              <Bot className="w-12 h-12 mx-auto mb-3 opacity-50" />
              <p>No bots deployed yet</p>
              <p className="text-sm mt-1">Click "Add Bot" to deploy your first bot</p>
            </div>
          ) : (
            <div className="divide-y divide-white/5">
              {bots.map((bot) => (
                <div 
                  key={bot.id}
                  className="p-4 hover:bg-white/5 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className={`w-3 h-3 rounded-full ${
                        bot.status === 'running' ? 'bg-green-500 animate-pulse' : 'bg-gray-500'
                      }`} />
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-semibold text-white">{bot.bot_name}</h4>
                          {bot.status === 'running' ? (
                            <CheckCircle className="w-4 h-4 text-green-400" />
                          ) : (
                            <XCircle className="w-4 h-4 text-gray-500" />
                          )}
                        </div>
                        <div className="flex items-center gap-4 text-xs text-gray-400 mt-1">
                          <span className="font-mono">Port: {bot.assigned_port}</span>
                          <span className="font-mono">Container: {bot.container_name}</span>
                        </div>
                        <p className="text-xs text-gray-500 mt-1 font-mono">
                          API Key: {bot.bot_api_key.slice(0, 10)}...{bot.bot_api_key.slice(-4)}
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        className={`gap-1 ${
                          bot.status === 'running' 
                            ? 'text-red-400 border-red-400/30 hover:bg-red-400/10' 
                            : 'text-green-400 border-green-400/30 hover:bg-green-400/10'
                        }`}
                        onClick={() => toggleBotStatus(bot)}
                      >
                        {bot.status === 'running' ? (
                          <>
                            <Square className="w-3 h-3" />
                            Stop
                          </>
                        ) : (
                          <>
                            <Play className="w-3 h-3" />
                            Start
                          </>
                        )}
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="text-red-400 border-red-400/30 hover:bg-red-400/10"
                        onClick={() => deleteBot(bot.id, bot.bot_name)}
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </ScrollArea>
      </div>

      {/* Docker Compose Preview */}
      {bots.length > 0 && (
        <div className="bg-gray-900/50 rounded-xl border border-white/10 p-4">
          <h4 className="font-semibold text-white mb-3 flex items-center gap-2">
            <Server className="w-4 h-4" />
            Generated docker-compose.yml
          </h4>
          <pre className="text-xs font-mono text-gray-400 overflow-x-auto">
{`version: '3.8'
services:
${bots.map(bot => `  ${bot.container_name}:
    image: node:20-alpine
    ports:
      - "${bot.assigned_port}:${bot.assigned_port}"
    environment:
      - BOT_TOKEN=\${${bot.container_name.toUpperCase().replace(/-/g, '_')}_TOKEN}
      - PORT=${bot.assigned_port}
    restart: always`).join('\n')}`}
          </pre>
        </div>
      )}
    </div>
  );
}
